Repository Nexters/Mohanyang-iOS, pull requests merged in 2024-12, with the labels that each got.

#61 [SCRUM-60] 타이머 알림음
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Module/Core.swift
  Projects/App/Resources/DEV/timer_end_sound.caf
  Projects/App/Resources/PROD/timer_end_sound.caf
  Projects/Core/AudioClient/Interface/AudioClientInterface.swift
  Projects/Core/AudioClient/Project.swift
  Projects/Core/AudioClient/Sources/AudioClient.swift
  Projects/Domain/PushService/Sources/Model/LocalPushNotiContent.swift
  Projects/Domain/PushService/Sources/PushService.swift
  Projects/Feature/PomodoroFeature/Sources/FocusPomodoro/FocusPomodoroCore.swift
  Projects/Feature/PomodoroFeature/Sources/RestPomodoro/RestPomodoroCore.swift
  Projects/Shared/DesignSystem/Project.swift
  Projects/Shared/DesignSystem/Resources/Sound/timer_end_sound.mp3
Labels: enhancement

#63 [SCRUM-102] mvp2차 지현 QA - 1
  Projects/Domain/CatService/Interface/Model/CatTemplate.swift
  Projects/Domain/CatService/Interface/Model/SomeCat.swift
  Projects/Feature/CatFeature/Sources/NamingCat/NamingCatCore.swift
  Projects/Feature/CatFeature/Sources/NamingCat/NamingCatView.swift
  Projects/Feature/CatFeature/Sources/SelectCat/SelectCatView.swift
  Projects/Feature/MyPageFeature/Sources/MyPage/MyPageCore.swift
  Projects/Feature/MyPageFeature/Sources/MyPage/MyPageView.swift
  Projects/Shared/DesignSystem/Sources/Component/InputField/InputField.swift
Labels: bug

#65 [SCRUM-105] mvp2차 QA 지현 - 2
  Projects/Feature/CatFeature/Sources/SelectCat/SelectCatCore.swift
  Projects/Feature/HomeFeature/Sources/Home/HomeView.swift
  Projects/Feature/MyPageFeature/Sources/MyPage/MyPageCore.swift
  Projects/Shared/DesignSystem/Resources/Image.xcassets/16/16_offline.imageset/16_offline.svg
  Projects/Shared/DesignSystem/Resources/Image.xcassets/16/16_offline.imageset/Contents.json
Labels: bug

#67 [SCRUM-109] 타임피커 스크롤 버그 수정
  Projects/Feature/HomeFeature/Sources/WheelPicker/WheelPicker.swift
Labels: bug

#68 [SCRUM-110] 2차 MVP 버그 수정
  Projects/Feature/Feature/Sources/AppView.swift
  Projects/Feature/HomeFeature/Sources/Home/HomeCore.swift
  Projects/Feature/HomeFeature/Sources/Home/HomeView.swift
  Projects/Feature/HomeFeature/Sources/TimeSelect/TimeItem.swift
  Projects/Feature/HomeFeature/Sources/TimeSelect/TimeSelectCore.swift
  Projects/Feature/PomodoroFeature/Sources/FocusPomodoro/FocusPomodoroCore.swift
  Projects/Feature/PomodoroFeature/Sources/FocusPomodoro/FocusPomodoroView.swift
  Projects/Feature/PomodoroFeature/Sources/Helper/Helper.swift
  Projects/Feature/PomodoroFeature/Sources/Pomodoro/PomodoroCore.swift
  Projects/Feature/PomodoroFeature/Sources/Pomodoro/PomodoroView.swift
  Projects/Feature/PomodoroFeature/Sources/RestPomodoro/RestPomodoroCore.swift
  Projects/Feature/PomodoroFeature/Sources/RestPomodoro/RestPomodoroView.swift
  Projects/Feature/PomodoroFeature/Sources/RestWaiting/RestWaitingCore.swift
  Projects/Feature/PomodoroFeature/Sources/RestWaiting/RestWaitingView.swift
Labels: bug, enhancement
